name: '[💚] Build'

on:
    - push

jobs:
    build:
        name: '[💚] Build'
        runs-on: 'ubuntu-latest'
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Set yarn version to latest stable
              run: |
                  corepack enable
                  yarn set version latest

            - name: Install dependencies
              run: |
                  yarn install --immutable

            - name: Run CI Script
              run: |
                  yarn ci

            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  message: 'chore: updates by CI'
